fix: Update dllmap with correct libpcap filename on startup

diff --git a/pro/Peach/peach b/pro/Peach/peach
--- a/pro/Peach/peach
+++ b/pro/Peach/peach
@@ -4,6 +4,7 @@
 
 OS=unknown
 DIST=unknown
+DIST_LIKE=unknown
 DIST_VERSION=unknown
 
 if [ "$(uname)" == "Darwin" ]; then
@@ -17,6 +18,7 @@ elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
 		# freedesktop.org and systemd
 		. /etc/os-release
 		DIST=$ID
+		DIST_LIKE=$ID_LIKE
 		DIST_VERSION=$VERSION_ID
 	elif type lsb_release >/dev/null 2>&1; then
 		# linuxbase.org
@@ -29,7 +31,7 @@ elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
 		DIST_VERSION=$DISTRIB_RELEASE
 	elif [ -f /etc/debian_version ]; then
 		# Older Debian/Ubuntu/etc.
-		DIST=Debian
+		DIST=debian
 		DIST_VERSION=$(cat /etc/debian_version)
 	elif [ -f /etc/SuSe-release ]; then
 		# Older SuSE/etc.
@@ -84,10 +86,40 @@ esac
 # Update dllmap as needed
 if [ "$OS" == "linux" ]; then
 
-	PCAP=`ldconfig -p | grep libpcap | cut -d ' ' -f 1 | tr -d '[:space:]'`
+	# Find ldconfig.  On suse /sbin is not in non-admin paths
+	LDCONFIG=ldconfig
+	if ! hash ldconfig 2>/dev/null; then
+		if [ -x "/sbin/ldconfig" ]; then
+			LDCONFIG=/sbin/ldconfig
+		elif [ -x "/bin/ldconfig" ]; then
+			LDCONFIG=/bin/ldconfig
+		elif [ -x "/usr/bin/ldconfig" ]; then
+			LDCONFIG=/usr/bin/ldconfig
+		elif [ -x "/usr/sbin/ldconfig" ]; then
+			LDCONFIG=/usr/sbin/ldconfig
+		elif [ -x "/usr/local/bin/ldconfig" ]; then
+			LDCONFIG=/usr/local/bin/ldconfig
+		elif [ -x "/usr/local/sbin/ldconfig" ]; then
+			LDCONFIG=/usr/local/sbin/ldconfig
+		else
+			echo ""
+			echo "Unable to locate ldconfig.  Please add to your path"
+			echo "and try again."
+			echo ""
+			exit 1
+		fi
+	fi
+
+	# find pcap
+	PCAP=`$LDCONFIG -p | grep libpcap | cut -d ' ' -f 1 | tr -d '[:space:]'`
 	if [ ! -z "$PCAP" ]; then
 		#echo "PCAP: '$PCAP'"
 		sed -i "s/libpcap.so[^\"]*/$PCAP/g" ${DIRNAME}/SharpPcap.dll.config
+	else
+		echo ""
+		echo "Error: libpcap not found.  Please install and try again."
+		echo ""
+		exit 1
 	fi
 
 fi
